load("//tools:shared_library.bzl", "idto_cc_shared_library")

idto_cc_shared_library(
  name = "shared_library",
  deps = [
    "//idto/common",
    "//idto/traj_opt:traj_opt",
  ],
  visibility = ["//visibility:public"],
)
